version: '3.8'

services:
  main-db:
    image: postgres:latest
    container_name: main-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 15982
    ports:
      - "5433:5432"
    volumes:
      - main-db-data:/var/lib/postgresql/data

  test-db:
    image: postgres:latest
    container_name: test-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 15982
    ports:
      - "5434:5432"
    volumes:
      - test-db-data:/var/lib/postgresql/data

volumes:
  main-db-data:
  test-db-data:
